First commit
EvilBorsch/Task_1 pull request #1
Opened 2019-10-07 16:02 UTC by EvilBorsch

2019-10-07 16:21 UTC, leshiy1295 commented
Видимо, отвалилась интеграция с Travis. Нужно её починить

2019-10-07 17:31 UTC, EvilBorsch commented
Починено

2019-10-08 11:45 UTC, leshiy1295 requested changes
Когда всё поправите - отпишитесь о готовности к повторному ревью отдельным комментарием
к следующей итерации уже необходимо доработать CI, добавив в него все необходимые проверки (см. комментарии)

2019-10-08 11:45 UTC, leshiy1295 commented on .travis.yml
> +                    # и, скажем, python -- никакой. Но пусть будет cpp.
комментарии, не относящиеся к делу, не нужны

2019-10-08 11:45 UTC, leshiy1295 commented on .travis.yml
> +  - gh-pages
зачем это?

2019-10-08 11:45 UTC, leshiy1295 commented on .travis.yml
> +    - ctest --output-on-failure
сейчас нет тестов, запускаемых таким образом

2019-10-08 11:45 UTC, leshiy1295 commented on .travis.yml
> +deploy:
что это?

2019-10-08 11:45 UTC, leshiy1295 commented on ci/travis/install-linux
> +sudo apt-get install -qq g++-5
зачем нужен g++ в данном случае?

2019-10-08 11:45 UTC, leshiy1295 commented on ci/travis/install-linux
> +    sudo apt-get install -y liblua5.2-dev:i386
зачем нужны эти библиотеки?

2019-10-08 11:45 UTC, leshiy1295 commented on main.c
> +#include <assert.h>
include стоит располагать в алфавитном порядке

2019-10-08 11:45 UTC, leshiy1295 commented on main.c
> +#define Tower struct Tower
используйте typedef...

2019-10-08 11:45 UTC, leshiy1295 commented on main.c
> +#define __Carr struct __Carr
зачем нужны такие __ в начале?
как правило, подобные названия резервируются в стандартных библиотеках...

2019-10-08 11:45 UTC, leshiy1295 commented on main.c
> +__Carr {
что такое Carr - непонятно из названия...

2019-10-08 11:45 UTC, leshiy1295 commented on main.c
> +    __Carr *list[3][4];         //массив длинны 3 на 4 т.к у нас 3 параметра для цели и 4 для расположения
откуда взяты эти магические константы?
программа должна работать для произвольного количества объектов

2019-10-08 11:45 UTC, leshiy1295 commented on main.c
> +void __print(const Tower tw) {
обычно методы для структур имеют в качестве префикса название типа структуры
это своего вида указание на namespace

2019-10-08 11:45 UTC, leshiy1295 commented on .travis.yml
> +        tags:     true
нету cpplint, cppcheck, тестов + valgrind + coverage.
Всё кроме последнего должно быть обязательно добавлено перед подачей на повторное ревью
Тесты позволят получить максимальный балл при выполнении прочих условий

2019-10-08 11:45 UTC, leshiy1295 commented on main.c
> +    if ((cr->real_size == 0 && cr->buffer_size == 0)) {      //если массив пустой, то нужно воткнуть первый элемент
что если cr == NULL?

2019-10-08 11:45 UTC, leshiy1295 commented on main.c
> +            errno = EDOM;               //Выводим ошибку если память не выделилась
тут ничего не выводится...

2019-10-08 11:45 UTC, leshiy1295 commented on main.c
> +            assert( 1 == 0);
в таком случае вся память, которая выделялась ранее, не будет освобождена, что некорректно
необходимо предусмотреть правильное завершение работы программы в подобных случаях

2019-10-08 11:45 UTC, leshiy1295 commented on main.c
> +        else cr->arr=temp;
не стоит экономить на строках и скобках {}

2019-10-08 11:45 UTC, leshiy1295 commented on main.c
> +int main() {
программа должна быть организована следующим образом:
- интерфейс - прототипы функций и типов
- main, который не содержит никакой логики и только вызывает функции:
-- инициализации и чтения (которая уже внутри себя непосредственно считывает что-то от пользователя и возвращает сформированную структуру)
-- обработки - основная логика программы
-- вывода результата и освобождения ресурсов
- реализация интерфейса - определение функций

2019-10-08 11:45 UTC, leshiy1295 commented on main.c
> +    /*char a[1024];
комментариев с нерабочим кодом быть не должно

2019-10-08 11:45 UTC, leshiy1295 commented on main.c
> +    Tower test = {1, 2, 3, "hotel", "EU"};
тесты необходимо вынести в отдельный таргет и автоматически запускать на CI с подсчётом coverage

2019-10-08 11:45 UTC, leshiy1295 commented on main.c
> +    Tower test9 = {3, 2, 5, "asdasdas", "SWA"};
должны быть также тесты на некорректный ввод

2019-10-08 11:45 UTC, leshiy1295 commented on main.c
> +    cr->real_size++; // и начинаем мы с 0 (поэтому если нужно запихнуть первый элемент будет 0++)
стоит избегать комментариев - код должен быть написан понятно и не нуждаться в доп. пояснениях
если же комментарии добавляются, то стоит их писать в корректном стиле

2019-10-08 11:45 UTC, leshiy1295 commented on main.c
> +        if (temp!=NULL)                                         //Если память не выделилась, спасаем старые данные
лучше сначала обработать некорректный кейс
+ не стоит экономить на пробелах

2019-10-08 11:45 UTC, leshiy1295 commented on main.c
> +            assert(0==1);
такие выходы недопустимы
более того, assert обычно работают только в debug-режиме, а в release - отключаются и просто игнорируются

2019-10-08 11:45 UTC, leshiy1295 commented on main.c
> +    for (size_t i = 0; i < bd->real_size; i++) {      //если массив пустой то мы ничего не запринтим
что если bd == NULL?

2019-10-08 11:45 UTC, leshiy1295 commented on main.c
> +void printDB(const DataBase db) {
должен быть единый стиль оформления названий функций
в C принят snake_case

2019-10-08 11:45 UTC, leshiy1295 commented on main.c
> +    if (strncmp(tw.region, "EU", 2) == 0) region_purpose = 0;
а что если будет "RU" или какой-то другой неизвестный регион?
программа должна работать для произвольных наборов входных данных

2019-10-08 11:45 UTC, leshiy1295 commented on main.c
> +    size_t target_purpose = 2; //двойка для другого
магические константы

2019-10-08 11:45 UTC, leshiy1295 commented on main.c
> +void add_to_DB(Tower tw, DataBase db) {
точно ли тут нужно передавать структуры по значению, а не по указателю?
нужно ли здесь добавить const?

2019-10-08 11:45 UTC, leshiy1295 commented on main.c
> +
отступы тоже должны быть осмысленными
просто так их оставлять - не дело

2019-10-08 11:45 UTC, leshiy1295 commented on main.c
> +    for (size_t i = 0; i < 3; i++) {
захардкоженные константы

2019-10-08 11:45 UTC, leshiy1295 commented on main.c
> +void delDB(DataBase *db){
что если db == NULL?

2019-10-08 11:45 UTC, leshiy1295 commented on main.c
> +            __Carr *temp = (__Carr *) malloc(sizeof(Tower)*1);
*1 - не нужно

2019-10-08 11:45 UTC, leshiy1295 commented on main.c
> +
что если db == NULL?

2019-10-08 11:45 UTC, leshiy1295 commented on main.c
> +    printDB(db);
должна производиться автоматическая проверка результата
простой вывод print и ручной просмотр вывода не подойдёт

2019-10-08 11:45 UTC, leshiy1295 commented on .travis.yml
> +dist:     trusty    # используем Ubuntu 14.04 Trusty Tahr (а не 12.02 Precise Pangolin)
можно взять более легковесный образ - полноценная ОС не нужна для запуска пары проверок

2019-10-08 11:45 UTC, leshiy1295 commented on CMakeLists.txt
> +if ("${TARGET_CPU}" STREQUAL "amd64")
в выводе от CI есть ряд замечаний по CMake-файлу - их тоже стоит поправить

2019-10-09 12:25 UTC, EvilBorsch commented
Исправлены замечания + добавлены проверки на запуск функций с нулевыми указателями( такой ситуации никогда не будет если пользователь запустил функцию create_BD( если бы это был c++, она была бы в конструкторе, но тут его нет))) ).
Отвечаю на вопросы на которых нет исправления:
1) only gh pages нужен для того чтобы travis не заходил в master
2) если будет "RU" то это считается другим region, и возьмётся ячейка в двумерном массиве в котором хранятся элемент с другим регионом и той целью которая необходима( в каждой ячейке двумерного массива хранится расширяемый массив динамический) (( как пронумерованный камод) ((( но я дал им название)))
3) Тесты буду добавлять позже, но cppechk и valgrind добавил.

2019-10-09 12:52 UTC, leshiy1295 requested changes

2019-10-09 12:52 UTC, leshiy1295 commented on main.c
> +#include <stdio.h>
нет условия задачи

2019-10-09 12:52 UTC, leshiy1295 commented on .travis.yml
> +  - gh-pages
github-pages у Вас не используется...
вопрос остаётся открытым

2019-10-09 12:52 UTC, leshiy1295 commented on .travis.yml
> +  - /.*/
зачем это ограничение?

2019-10-09 12:52 UTC, leshiy1295 commented on .travis.yml
> +    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then valgrind --error-exitcode=1 --leak-check=full --show-leak-kinds=all ./main ; fi
можно было бы вынести в отдельный скрипт, как это сделано для install...

2019-10-09 12:52 UTC, leshiy1295 commented on README.rst
> +    :target: https://travis-ci.org/EvilBorsch/task_1_test
нужен вывод в Pull Request состояния сборки
причём на каждую проверку - своя иконка (тесты/сборка/проверки...)

2019-10-09 12:52 UTC, leshiy1295 commented on main.c
> +#define possible_target_count 3 //офисные,гостиничные, другие(другие это 3 тип)
"офисные,гостиничные" - это пример ввода, а не обязательные поля
поэтому ограничения по константам 3 и 4 не нужны...
программа должна работать для любых типов
сортировка - например, по алфавиту

2019-10-09 12:52 UTC, leshiy1295 commented on main.c
> +void delDB(Data_base *db);
снова есть расхождения по именованию

2019-10-09 12:52 UTC, leshiy1295 commented on main.c
> +void print_Tower(const Tower* tw) {
реализация интерфейса должна идти после main

2019-10-09 12:52 UTC, leshiy1295 commented on main.c
> +    if (li==NULL){
NULL может быть всегда, так как никаких гарантий того, что функция не будет использоваться где-нибудь ещё - нет. Плюс, не факт, что на той стороне будет известна реализация

2019-10-09 12:52 UTC, leshiy1295 commented on main.c
> +
не поправлено

2019-10-09 12:52 UTC, leshiy1295 commented on main.c
> +        for (size_t j = 0; j < possible_region_count; j++) {
предпочитайте ++i вместо i++

2019-10-09 12:52 UTC, leshiy1295 commented on main.c
> +    if (strncmp(tw->target, "office", 6) == 0) target_purpose = 0;
всё ещё магические константы
их быть ни в коем случае не должно
как минимум, они должны быть именованными
так как эти числа однозначно проверяются по длине строки
+ есть функция strcmp - почему бы не использовать её?

2019-10-09 12:52 UTC, leshiy1295 commented on main.c
> +    Data_base db;
не должно быть одной функции со всеми тестами
если какой-то тест не пройдёт, то должна быть возможность пройти всем остальным тестам
для этого фреймворки и используются обычно
если хотите делать без фреймворка - нужно это предусмотреть самостоятельно. Например, можно вынести каждый тест в отдельный файл и запускать их через внешний sh в цикле по всем файлам в директории с тестами

2019-10-09 12:52 UTC, leshiy1295 commented on main.c
> +    Tower test3 = {3, 2, 5, "office", "ME"};
даже если бы делать все тесты тут, то почему бы не сделать через массив и цикл?

2019-10-09 12:52 UTC, leshiy1295 commented on main.c
> +    print_DB(&db);
вывод сейчас никак и нигде не проверяется. Смыслов от таких тестов на CI отсутствует.
Нужно либо проверить корректный вывод программы в целом (end-to-end тесты), либо проверять вывод функций непосредственно перед выводом (unit-тесты).

2019-10-09 12:52 UTC, leshiy1295 commented on main.c
> +    test();
сделайте унифицированный интерфейс (например, через аргументы командной строки) или через stdin, через который можно передавать тесты
+ сейчас программой невозможно пользоваться с произвольными значениями. Должен быть ввод какой-то при обычном сценарии использования. Ввод может быть как из файла, так и из stdin. Последний вариант - более универсальный

2019-10-09 12:52 UTC, leshiy1295 commented on main.c
> +    add_to_list(db->list[target_purpose][region_purpose],tw);              //вставляем Tower в необходимое место, найденное раньше
что если внутри add_to_list произошла ошибка выделения памяти?
кажется, что её нужно донести до пользователя сразу, а не просто проигнорировать и продолжить добавлять другие записи...

2019-10-09 12:52 UTC, leshiy1295 commented on main.c
> +        perror("DB IS NOT CREATED");
неправильно, что внутренняя функция напрямую что-то выводит
всё, что должен сделать функция - это вернуть код операции (успех/ошибка), так как не знает, как она используется
вывод пользователю может быть сделан, например, в main, которая передаст соответствующей функции вывода результата код ошибки. На этом уровне (уровень клиента/интерфейса взаимодействия с ним) уже есть вся информация о том, куда нужно вывести ошибку

2019-10-09 12:52 UTC, leshiy1295 commented on .travis.yml
> +    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then lcov --version ; fi
как сейчас используется coverage, и где можно посмотреть отчёт?

2019-10-09 12:52 UTC, leshiy1295 commented on .travis.yml
> +    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then g++ --version ; fi
зачем выводить версии утилит непосредственно после их выполнения?

2019-10-09 12:52 UTC, leshiy1295 commented on .travis.yml
> +    - g++ -g -Wall -Wextra main.c -o main
почему программа на C компилируется при помощи g++?
+ также должны быть поправлены все warning-и - рекомендую добавить -Wpedantic -Werror

2019-10-09 12:52 UTC, leshiy1295 commented on ci/travis/install-osx
> +
зачем этот файл, если он пустой?

2019-10-09 12:52 UTC, leshiy1295 commented on main.c
> +    List *list[possible_target_count][possible_region_count];         //двумерный массив,внутри каждой ячейки которого наши продвинутые List'ы
сейчас по сути в самой программе захардкожены поля, по которым нужно сортировать
если бы нужно было добавить ещё одно поле, то сейчас это было бы сделать затруднительно
нужно предусмотреть более общий интерфейс - например, поддержать функцию сортировки, принимающей функцию попарного сравнения элементов, в которой уже будет приниматься решение на основе тех или иных полей

2019-10-09 12:52 UTC, leshiy1295 commented on main.c
> +    create_DB(&db);
почему бы create_DB не возвращать указатель?
а в delDB его освобождать?

2019-10-09 12:52 UTC, leshiy1295 commented on main.c
> +            free(db->list[i][j]->arr);
что если db->list[i][j] == NULL?

2019-10-09 12:52 UTC, leshiy1295 commented on main.c
> +            free(db->list[i][j]->arr);
что если бы в list[i][j] содержалось бы больше полей?
стоит вынести в отдельную функцию для каждой записи

2019-10-09 12:52 UTC, leshiy1295 commented on main.c
> +        perror("Database is not created");
аналогично - нужно пробросить код ошибки наверх и обработать на приёмной стороне

2019-10-09 13:48 UTC, EvilBorsch commented
Как мне нужно сортировать поля? В задании сказано: Составить с ее использованием программу вывода информации
 * обо всех зданиях с группировкой сначала по назначению (офисные, гостиничные и т.д.),
 * затем — по региону расположения (Европа, Ближний Восток, Юго-Восточная Азия и т.д.).

Я должен сгруппировать по двум признакам, с учётом двух функций сортировки? Или я должен сгруппировать по одному признаку с учетом функции сортировки и вывести результат, а потом сгруппировать по другому признаку с учетом его личной функции сортировки и вывести результат, чтобы получилось два результата.

2019-10-09 14:05 UTC, leshiy1295 commented
По двум сразу. Например:
hotel, RU, 5
office, EU, 1
office, EU, 2
office, RU, 3
Тут сначала вывелись все hotel (так как h < o), а внутри группы office сначала вывелись все EU (так как E < R).
Но это должно быть оформлено в виде отдельной функции попарного сравнения, которую можно передать функции сортировки. В качестве примера можете посмотреть на реализацию стандартной функции qsort

2019-10-09 14:16 UTC, EvilBorsch commented
Как я понял задачу: мы группируем по одному признаку в зависимости от заданной функции сравнения(например по алфавиту), в которой прописано что если цели совпадают мы уже смотрим на функцию сравнения регионов, это как я понял ваши слова.

2019-10-09 14:24 UTC, leshiy1295 commented
Да, примерно так. Конкретно в этом случае необязательно для сравнения каждого признака делать отдельную функцию, а можно всё явно в одной сравнить.
Но отдельные функции - это не ошибка :)
Важно, чтобы эта общая функция сравнения реализовывала интерфейс для функции сортировки.

2019-10-10 13:06 UTC, EvilBorsch commented
Поправил, тесты пока не добавлены, в функции test только пример функций программы

2019-10-13 16:08 UTC, leshiy1295 requested changes

2019-10-13 16:08 UTC, leshiy1295 commented on .travis.yml
> +    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then valgrind --error-exitcode=1 --leak-check=full --show-leak-kinds=all ./main ; fi
не поправлено...

2019-10-13 16:08 UTC, leshiy1295 commented on ci/travis/install-linux
> +sudo apt-get install -qq g++-5
не поправлено...

2019-10-13 16:08 UTC, leshiy1295 commented on main.c
> +    test();
нужно было предусмотреть обычный ввод с клавиатуры и запуск тестов либо в отдельной программе, либо с аргументами командной строки/флагом -D..

2019-10-13 16:08 UTC, leshiy1295 commented on main.c
> +            perror("OS didnt give memory");
внутренние функции не должны ничего печатать...

2019-10-13 16:08 UTC, leshiy1295 commented on main.c
> +    temp->buffer_size=arr_size;
что если malloc вернёт ошибку?

2019-10-13 16:08 UTC, leshiy1295 commented on main.c
> +    free(li->arr);
что если li == NULL?

2019-10-13 16:08 UTC, leshiy1295 commented on main.c
> +    else{
else не нужен

2019-10-13 16:08 UTC, leshiy1295 commented on main.c
> +    List* temp_li=(List*)malloc(sizeof(List));
что если malloc вернёт ошибку?

2019-10-13 16:08 UTC, leshiy1295 commented on main.c
> +    char buffer[1024];
что если ввести 1025 символов?

2019-10-13 16:08 UTC, leshiy1295 commented on main.c
> +        temp.target = (char*) malloc(sizeof(char)*strlen(buffer));
нужно всегда обрабатывать ошибки malloc...

2019-10-13 16:08 UTC, leshiy1295 commented on main.c
> +    //List* li2=input_List_from_keyboard();
комментариев с нерабочим кодом быть не должно

2019-10-13 16:08 UTC, leshiy1295 commented on main.c
> +    Tower test = {1, 2, 3, "abc", "cus"};
стоило разнести на отдельные функции
и использовать массив структур, а не test1, test2, ...

2019-10-13 16:08 UTC, leshiy1295 commented on main.c
> +    print_List(li);
вывод не проверяется => автотестов нет

2020-02-06 01:21 UTC, merged